name: vulcanos
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: Build vulcanos
      run: |
        sudo apt update && sudo apt install -y nasm grub-pc-bin mtools xorriso
        sudo ln -s /usr/bin/gcc /usr/bin/i686-elf-gcc
        sudo ln -s /usr/bin/ld /usr/bin/i686-elf-ld
        make clean all
